paths:
  search_info: /uapi/domestic-stock/v1/quotations/search-info
  inquire_price: /uapi/domestic-stock/v1/quotations/inquire-price
  market_cap: /uapi/domestic-stock/v1/ranking/market-cap
  asking_price: /uapi/domestic-stock/v1/quotations/inquire-asking-price-exp-ccn
  time_conclude: /uapi/domestic-stock/v1/quotations/inquire-time-itemconclusion
  search_stock: /uapi/domestic-stock/v1/quotations/search-stock-info
  ranking_fluctuation: /uapi/domestic-stock/v1/ranking/fluctuation
  ranking_volume: /uapi/domestic-stock/v1/quotations/volume-rank
  ranking_foreign: /uapi/domestic-stock/v1/quotations/inquire-foreign
  item_news: /uapi/domestic-stock/v1/quotations/news-title
  etf_info: /uapi/etfetn/v1/quotations/inquire-price
  multi_price: /uapi/domestic-stock/v1/quotations/intstock-multprice
  inquire_daily_itemchartprice: /uapi/domestic-stock/v1/quotations/inquire-daily-itemchartprice      # 기간별 시세 (일/주/월/년)
  inquire_time_itemchartprice: /uapi/domestic-stock/v1/quotations/inquire-time-itemchartprice        # 당일 분봉 조회
  inquire_time_daily_itemchartprice: /uapi/domestic-stock/v1/quotations/inquire-time-dailychartprice # 일변 분봉 조회

  # 계좌/주문
  inquire_balance: /uapi/domestic-stock/v1/trading/inquire-balance
  order_cash: /uapi/domestic-stock/v1/trading/order-cash
  hashkey: /uapi/hashkey   # 선택: 없으면 코드에서 리터럴로 써도 됨

  # websocket
  approval_key: /oauth2/Approval
  real_time_price: /tryitout/H0STCNT0
params:
  fid_div_cls_code: "2"
  screening_code: "20174"
